blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/IoT-VN/poe2-temple-score/blob/master/AGENTS.md
    about: Check the documentation before creating an issue
